#!/usr/bin/env node
// Runs inside the container before the main runtime starts (see entrypoint.sh).
// Two jobs, both pure manifest inspection: report whether the manifest
// declares a browser:* capability so entrypoint.sh knows whether to start
// Xvfb/x11vnc/websockify, and separately report
// whether it declares browser:navigate:*/network:host:* so entrypoint.sh
// knows whether to start the egress broker — a deliberately different check
// from "needs a display": network:host:* apps need the broker but never
// Xvfb, and this is what makes the broker a capability any resident app can
// opt into, not something wired specifically for browser-native's Chromium
// launch flag. Lives inside @berth/sdk (not a loose script copied from
// docker-orchestrator) specifically so it can import @berth/manifest-schema
// through normal package resolution — pnpm's per-package node_modules only
// resolves declared dependencies, and @berth/sdk already declares
// @berth/manifest-schema as one.
//
// It used to have a third job: executing the manifest's on_install commands
// (once, tracked by a marker file). That ran as uid 0 with CAP_SYS_ADMIN and
// no Landlock domain — necessarily before one existed, since the capability
// policy is generated by the script entrypoint.sh calls immediately after
// this one. Any berth.yml was therefore arbitrary root code execution inside
// the sandbox meant to constrain it (REMEDIATION.md 1.5). on_install now runs
// as a Docker build layer instead, for both the dev and production targets —
// see @berth/docker-orchestrator's stageOnInstallScript() and
// docker/run-on-install.sh. Nothing executes it at container boot any more,
// which is also why the install-marker file is gone: there is no longer a
// boot-time action to run at most once.
//
// The SDK's own app.onInstall(fn) hook is unaffected and is the supported
// place for setup that must happen in-process — it runs from runtime.ts,
// inside the app's own already-Landlocked process, under its declared
// capabilities.
import { join } from "node:path";
import { loadManifest } from "@berth/manifest-schema";

// Relative to process.cwd() (the container's WorkingDir), not a hardcoded
// /app — the app's working directory varies depending on whether it's a
// standalone app (/app) or a pnpm workspace member (/workspace/<path>).
const MANIFEST_PATH = process.env.BERTH_MANIFEST_PATH ?? join(process.cwd(), "berth.yml");

async function main(): Promise<void> {
  const manifest = await loadManifest(MANIFEST_PATH);

  const needsBrowser = manifest.capabilities.some((cap) => cap.startsWith("browser:"));
  const needsEgressBroker = manifest.capabilities.some((cap) => cap.startsWith("browser:navigate:") || cap.startsWith("network:host:"));
  // A single comma-separated line, not two lines — entrypoint.sh's
  // `tail -n1` only ever captures the last stdout line, which needs to carry
  // both flags together.
  console.log(`${needsBrowser ? "1" : "0"},${needsEgressBroker ? "1" : "0"}`);
}

main().catch((err) => {
  console.error("[berth:lifecycle] fatal error:", err);
  process.exit(1);
});
