// Turns a results file into the scored table.
//
// The table is generated, never hand-written (BUILD_PLAN M2.2): every cell in
// it came out of a run, and the file it came from is named in the output. The
// scoring rules are deliberately unflattering:
//
//   - unmeasured and not-applicable are NOT passes. They are printed as
//     themselves and excluded from the denominator, and the count of each is
//     printed next to the score so a column that measured three rows cannot
//     look like a column that measured eleven.
//   - a row Berth fails stays red and links its REMEDIATION item.
//   - `berthNote` from checks.mjs is printed under the table whether or not
//     the cell passed — a pass resting on an unfinished mechanism says so.

import { CHECKS, CHECK_BY_ID } from "./checks.mjs";

const CELL = {
  contained: "🟢 contained",
  escaped: "🔴 escaped",
  unmeasured: "⚪ unmeasured",
  "not-applicable": "⚪ n/a",
  "not-run": "⚪ NOT RUN",
};

/** contained / (contained + escaped). Unmeasured and n/a never help a score. */
export function scoreHarness(harnessResult) {
  let contained = 0;
  let escaped = 0;
  let unmeasured = 0;
  let notApplicable = 0;
  for (const check of CHECKS) {
    const outcome = harnessResult?.results?.[check.id]?.outcome ?? "not-run";
    if (outcome === "contained") contained += 1;
    else if (outcome === "escaped") escaped += 1;
    else if (outcome === "not-applicable") notApplicable += 1;
    else unmeasured += 1;
  }
  const measured = contained + escaped;
  return { contained, escaped, unmeasured, notApplicable, measured, pct: measured === 0 ? null : Math.round((contained / measured) * 100) };
}

export function renderMarkdown(report) {
  const harnesses = report.harnesses;
  const ids = harnesses.map((h) => h.id);
  const lines = [];

  lines.push("# Containment benchmark results");
  lines.push("");
  lines.push(`Generated by \`bench/run.mjs\` on ${report.generatedAt}. Do not hand-edit — regenerate.`);
  lines.push("");
  lines.push(`Host: ${report.host.platform} / ${report.host.arch}, Docker kernel \`${report.host.kernelVersion ?? "unknown"}\` (${report.host.operatingSystem ?? "unknown"}).`);
  lines.push("");

  // --- scores ---------------------------------------------------------------
  lines.push("## Score");
  lines.push("");
  lines.push("| Harness | Contained | Escaped | Unmeasured | N/A | Score |");
  lines.push("|---|---|---|---|---|---|");
  for (const h of harnesses) {
    const s = scoreHarness(h);
    const score = s.pct === null ? "— (nothing measured)" : `**${s.pct}%** of ${s.measured} measured`;
    lines.push(`| ${h.title} | ${s.contained} | ${s.escaped} | ${s.unmeasured} | ${s.notApplicable} | ${score} |`);
  }
  lines.push("");
  lines.push("Score is `contained / (contained + escaped)`. Rows that could not be measured, or that a harness has no surface for, are excluded from the denominator and shown as their own columns — a harness is never rewarded for a row that did not run.");
  lines.push("");

  // --- the matrix -----------------------------------------------------------
  lines.push("## Rows");
  lines.push("");
  lines.push(`| Check | ${harnesses.map((h) => h.title).join(" | ")} |`);
  lines.push(`|---|${ids.map(() => "---").join("|")}|`);
  for (const check of CHECKS) {
    const cells = harnesses.map((h) => CELL[h.results?.[check.id]?.outcome ?? "not-run"] ?? "⚪ unknown");
    lines.push(`| **${check.title}** | ${cells.join(" | ")} |`);
  }
  lines.push("");

  // --- detail ---------------------------------------------------------------
  lines.push("## What each row tried, and what happened");
  lines.push("");
  for (const check of CHECKS) {
    lines.push(`### ${check.title}`);
    lines.push("");
    lines.push(`*${check.question}*`);
    lines.push("");
    lines.push(check.matters);
    lines.push("");
    for (const h of harnesses) {
      const result = h.results?.[check.id];
      const outcome = CELL[result?.outcome ?? "not-run"] ?? "⚪ unknown";
      lines.push(`- **${h.title}** — ${outcome}: ${result?.detail ?? "not run"}`);
    }
    if (check.berthNote) {
      lines.push("");
      lines.push(`> **Berth's own caveat on this row.** ${check.berthNote}`);
    }
    lines.push("");
  }

  // --- provenance -----------------------------------------------------------
  lines.push("## How each column was produced");
  lines.push("");
  for (const h of harnesses) {
    lines.push(`### ${h.title}`);
    lines.push("");
    lines.push(h.description);
    lines.push("");
    if (h.skipped) lines.push(`**NOT RUN.** ${h.skipped}`);
    else if (h.error) lines.push(`**FAILED.** ${h.error}`);
    else if (h.meta) lines.push(`\`\`\`json\n${JSON.stringify(h.meta, null, 2)}\n\`\`\``);
    lines.push("");
  }

  // The Berth column is only worth reading alongside whether the kernel tier
  // was live for that run — the same measurement `berth attest` records.
  const berth = harnesses.find((h) => h.id === "berth");
  const enforcement = berth?.meta?.enforcement;
  if (enforcement && !enforcement.error) {
    const reports = (enforcement.rulesetReports ?? []).map((r) => `${r.app}=${r.ruleset}`).join(", ");
    lines.push("## Was Berth's kernel tier actually live for this run?");
    lines.push("");
    lines.push(`Doctor probe: \`${enforcement.doctorProbe?.status}\`${enforcement.doctorProbe?.reason ? ` (${enforcement.doctorProbe.reason})` : ""}. agent-init reported: ${reports || "nothing"}.`);
    lines.push("");
    lines.push(
      enforcement.doctorProbe?.status === "enforcing"
        ? "Landlock was enforcing on this host, so the filesystem and network rows above measured the kernel tier."
        : "**Landlock was not enforcing on this host.** Berth's filesystem and network rows above did not measure a kernel boundary — see docs/mac-enforcement.md for a host where they do.",
    );
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}
